version: "3.9"
services:
  db:
    image: mongo
    container_name: dbmongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
     
      
    
